"""
telegram_sender.py
Sends the BTC chart image and analysis text to a Telegram bot/channel.
Uses the Telegram Bot HTTP API directly (no extra library needed).
"""

import os
import requests


TELEGRAM_API = "https://api.telegram.org/bot{token}/{method}"
MAX_CAPTION  = 1024   # Telegram caption limit for photos
MAX_MESSAGE  = 4096   # Telegram message text limit


def _url(method: str) -> str:
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    return TELEGRAM_API.format(token=token, method=method)


def _send_photo(chat_id: str, photo_path: str, caption: str = ""):
    """Send a photo with optional caption to Telegram."""
    with open(photo_path, "rb") as f:
        resp = requests.post(
            _url("sendPhoto"),
            data={
                "chat_id":    chat_id,
                "caption":    caption[:MAX_CAPTION],
                "parse_mode": "HTML",
            },
            files={"photo": f},
            timeout=30,
        )
    resp.raise_for_status()
    return resp.json()


def _send_message(chat_id: str, text: str):
    """Send a text message, splitting if it exceeds Telegram's 4096-char limit."""
    chunks = [text[i : i + MAX_MESSAGE] for i in range(0, len(text), MAX_MESSAGE)]
    for chunk in chunks:
        resp = requests.post(
            _url("sendMessage"),
            json={
                "chat_id":                  chat_id,
                "text":                     chunk,
                "disable_web_page_preview": True,
            },
            timeout=15,
        )
        resp.raise_for_status()


def send_analysis(chart_path: str, analysis_text: str):
    """
    Main function: sends chart image first, then the full analysis text.

    Args:
        chart_path:    Path to the PNG chart file
        analysis_text: Full analysis string generated by Claude
    """
    token   = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")

    if not token:
        raise EnvironmentError("TELEGRAM_BOT_TOKEN is not set.")
    if not chat_id:
        raise EnvironmentError("TELEGRAM_CHAT_ID is not set.")

    print("  -> Sending chart image...")
    _send_photo(chat_id, chart_path)

    print("  -> Sending analysis text...")
    _send_message(chat_id, analysis_text)

    print("  -> Telegram delivery complete.")
